In [20]:
import Feynman as fmn
import numpy as np

<a id=start></a>
# Table of Contents

1. [Instructions of use](#Instructions)
    1. [Momentum class](#Momentum)
        1. [Argument hierarchy](#Hierarchy)
        2. [Momentum Operations](#Operations)
        3. [Attributes and Methods](#A&M)
    2. [Gamma Matrices](#Gamma)
    3. [Physics functions](#Physics)
2. [Example of use](#Example_1)

<a id=Instructions></a>
# Instructions of use:

This code has the purpose of help doing the computations needed to evaluate Feynman diagrams and computations of the diferent associated measurable properties. Including an easy way to define 4-vectors with all the common operations and properties associated to the momenta. Other useful features of this library is the incoporation of Lorentz transformation.

[Return to Table](#start)
<a id=Momentum></a>
## Momentum class:

The main feature of this program is the class Momentum, it allows to define a 4-Momentum object, with some attributes like the p-slash matrices, a spinor associated or its mass.

To create a 4-Momentum object simply write in your code

In [21]:
p = fmn.Momentum()
print(p)

'' 4-Momentum, p=[0.15843166 0.49497173 1.26474986 0.5240985 ], p^2=-2.09


Now $p$ becomes a 4-Momentum object, by printing $p$ you can see its main attributes, the name (in this case it has no name and we only see the ' '), the contravariant coordinates and its square $p^2$. The coordinates have been setted in a random way, you can create different 4-Momentums using the arguments *'M'* and *'coord'*, and also give a name to the momentum using the *'name'* argument

In [22]:
p = fmn.Momentum(M=3) #Creates a 4-Momentum with mass=3
print(p)

p = fmn.Momentum(3) #Same as Momentum(M=3)
print(p)

coord = fmn.array([10, 1, 5, 2]) #Set a numpy 4-vector
p = fmn.Momentum(coord = coord) #Creates a 4-Momentum with the previous contravariant coordinates
print(p)

p = fmn.Momentum(name = 'p_1')
print(p)

p = fmn.Momentum(M=0.5, name='electron') #Creates a 4-Momentum with mass=0.5, fixing the coordinates and with name ='electron'.
print(p)

print(coord)
p = fmn.Momentum(M=0.5, coord=coord, name='electron') #Creates a 4-Momentum with mass=0.5 and coordinates=coord.
print(p)

'' 4-Momentum, p=[ 3.0605568   0.14279278  0.43426286 -0.39753482], p^2=9.00
'' 4-Momentum, p=[3.21270435 0.26985706 0.60729307 0.93799869], p^2=9.00
'' 4-Momentum, p=[10.  1.  5.  2.], p^2=70.00
'p_1' 4-Momentum, p=[ 1.29642172 -1.21662511 -0.63420709  1.97082899], p^2=-4.09
'electron' 4-Momentum, p=[ 2.46294748  2.16477755  0.07853267 -1.06003826], p^2=0.25
[10  1  5  2]
'electron' 4-Momentum, p=[5.5 1.  5.  2. ], p^2=0.25


Is important to notice that the mass and coordinates can be in conflict like this last example, we will talk about this later, but see that the energy of the 4-Momentum is changed to $E=\sqrt{m^2+|\vec{p}|^2}$.

There are two more things to know (more advanced) to have more control of your 4-Momentum. This are the *size* argument and the *'r'* coordinates.

Note that all the random Momenta created until now have a 3-Momentum of order 1. If for some reason we want the coordinates to be of a diferent order of magnitude, we can use the *size* argument as showed in the next cell.

Also, note that we have three posibilities until now, a completely random 4-Momentum, a random 3-Momentum with energy $E=\sqrt{m^2+|\vec{p}|^2}$, and a fixed 4-Momentum. But what happens if we want the 4-Momentum to have a fixed energy without specifying the 3-Momentum? Or we want the 3-Momentum to have $p_y=3$? 

This can be implemented using the *coord* argument, but using an *'r'* to mark what coordinates will be randomized.

In [23]:
# Size argument:
print('\033[1mSize argument:\033[0m', end='\n\n')

p, q = fmn.Momentum(M=1e3), fmn.Momentum(M=1e-3)
print('No size argument:', p)
print('No size argument:', q)

#The 3-momentum is always of order 1, this is how to change it:
p, q = fmn.Momentum(M=1e3, size=1e3), fmn.Momentum(M=1e-3, size=1e-3)
print('With size argument:', p) #Now the 3-momentum will be of order 1000
print('With size argument:', q) #Here the 3-momentum will be of order 0.001

Size argument:

No size argument: '' 4-Momentum, p=[ 1.00000219e+03 -3.32643157e-02 -1.19811154e+00  1.71694711e+00], p^2=1000000.00
No size argument: '' 4-Momentum, p=[ 1.22282176 -0.29170424  1.16485987 -0.23087264], p^2=0.00
With size argument: '' 4-Momentum, p=[2787.59212191  256.85759809 1863.36674273 1797.93169907], p^2=1000000.00
With size argument: '' 4-Momentum, p=[ 1.20100270e-03 -4.76551040e-04  4.62987082e-04  3.08148231e-05], p^2=0.00


In [24]:
#'r' coordinates:
print("\n\033[1m'r' coordinate:\033[0m", end='\n\n')

#Imagine we want an electron with energy E=1MeV. We can create its momentum as
m, E = 0.5, 1 #MeV
p = fmn.Momentum(m, name='electron') #This fixes the mass, but the energy is not 1
print(p)

#We can write a general 4-vector with energy E
p = fmn.Momentum(m, coord=fmn.array([E, 0, 0, 0]), name='electron')
print(p)
#But the energy is changed to impose m=0.5, so not a solution, the solution is to use 'r' coordinates:
p = fmn.Momentum(m, coord=fmn.array([1, 'r', 'r', 'r']), name='electron')
print(p)
#This has generated a random 3-vector fullfilling the condition $p^2=E^2-m^2$.

#What if we want a random 4-vector, but with p_y=3? Then againg 'r' coordinates is the solution
p = fmn.Momentum(10, coord=fmn.array(['r', 'r', 3, 'r']), size=10)
print(p)

#Or a 4-vector in the z direction:
p = fmn.Momentum(50, coord=fmn.array(['r', 0, 0, 'r']), size=50)
print(p)


'r' coordinate:

'electron' 4-Momentum, p=[ 1.03577728  0.09829705  0.32700311 -0.8403816 ], p^2=0.25
'electron' 4-Momentum, p=[0.5 0.  0.  0. ], p^2=0.25
'electron' 4-Momentum, p=[ 1.          0.03370665 -0.10152956 -0.85939258], p^2=0.25
'' 4-Momentum, p=[ 16.38559202 -12.49036426   3.          -1.86505407], p^2=100.00
'' 4-Momentum, p=[55.27416344  0.          0.         23.56338565], p^2=2500.00


<a id=Hierarchy></a>
[Return to Table](#start)
### Argument Hierarchy

Finally, to have all the possible control of your momenta we need to look at what happens when the mass and the coordinates are not compatible, as we have seen before, the mass is always the principal argument, and therefore any incompatiblility will be solved modifying the energy of the momentum. 

In [25]:
#When the 4-momentum is not compatible with the mass the energy is changed.
p = fmn.Momentum(M=1, coord=fmn.array([1, 1, 1, 1]))
print(p)

#Also, when using 'r' coordinates, there may be incopmatibilities:
p = fmn.Momentum(M=3, coord=fmn.array([2, 'r', 'r', 'r']))
print(p)
#In this case the energy will also be changed to allow the 4-momentum to have the correct mass.

'' 4-Momentum, p=[2. 1. 1. 1.], p^2=1.00
'' 4-Momentum, p=[ 3.20670637  0.14474036 -0.62475115  0.9336498 ], p^2=9.00


[Return to Table](#start)
<a id=Operations></a>
### Momentum Operations
Now we know how to create a 4-Momenta objects, what can we do with that? Well, first of all let's look at some of their methods. The 4-Momenta objects have following operations:

In [26]:
#Sum of 4-Momenta:
print('\033[1mSum of Momenta:\033[0m', end='\n\n')
p1, p2 = fmn.Momentum(M=5, name='p1'), fmn.Momentum(3, name='p2')
print(p1, p2, sep='\n')
q = p1 + p2
print(q)
#This creates another 4-Momentum with coordinates equal to the sum of the coordinates of p1 and p2.

#The default name is 'p1 + p2' but maybe one want to give a specific name, this can be done in two ways, one is with the 
#'name' attribute (we will see the attributes in a moment), the other is using the __add__ method:
q.name = 'Named with attribute'
print('\n', q, sep='')

#Fot the second way, we need to know that when we write p1+p2 python calls the function p1.__add__(p2), in this case this
#function takes an extra argument that is the name, so we can set the name directly by
q = p1.__add__(p2, 'Named with method')
print(q)

#Subtraction of Momenta
print('\n\033[1mSubtraction of Momenta:\033[0m', end='\n\n')
#In the same way we can sum momenta, we can subtract them
q = p1 - p2
print(q)
#Again we can change its name
q.name = 'Named with attribute'
print(q)
q = p1.__sub__(p2, 'Named with method')
print(q)

#Multiplication of Momenta:
print('\n\033[1mProduct of Momenta:\033[0m', end='\n\n')
#This haves two options; the multiplication by scalars, which returns another 4-Momentum:
p = fmn.Momentum(M=2, name='p')
print(p)
q1 = 2*p
q2 = p*3
print(q1, q2, sep='\n')
#Note that the multiplication works from both sides. 
#The other option is the multiplication by another 4-Momentum:
#This returns a number, that is the scalar product (with Minkowski metric +---) of the two 4-Momenta.
print('q1*q2:', q1*q2)

#Finally, we can also take integer powers:
print('\n\033[1mPowers of a Momentum:\033[0m', end='\n\n')
#Even powers give a number, defined by p^n = (sqrt(p^2))^n:
p = fmn.Momentum(2, name='p')
print(p)
print(f'p^2={p**2}', f'p^4={p**4}', f'p^6={p**6}', sep='\n')
#Odd powers give a 4-Momentum defined as p^n = p^(n-1) * p
print(p)
print(f'p^3={p**3}', f'p^5={p**5}', sep='\n')

Sum of Momenta:

'p1' 4-Momentum, p=[ 5.81200437  2.68674171 -0.66069159  1.06033031], p^2=25.00
'p2' 4-Momentum, p=[3.23120158 0.99827477 0.53350369 0.39935572], p^2=9.00
'p1 + p2' 4-Momentum, p=[ 9.04320595  3.68501648 -0.1271879   1.45968603], p^2=66.05

'Named with attribute' 4-Momentum, p=[ 9.04320595  3.68501648 -0.1271879   1.45968603], p^2=66.05
'Named with method' 4-Momentum, p=[ 9.04320595  3.68501648 -0.1271879   1.45968603], p^2=66.05

Subtraction of Momenta:

'p1 - p2' 4-Momentum, p=[ 2.58080278  1.68846695 -1.19419527  0.6609746 ], p^2=1.95
'Named with attribute' 4-Momentum, p=[ 2.58080278  1.68846695 -1.19419527  0.6609746 ], p^2=1.95
'Named with method' 4-Momentum, p=[ 2.58080278  1.68846695 -1.19419527  0.6609746 ], p^2=1.95

Product of Momenta:

'p' 4-Momentum, p=[2.88459398 0.37537688 0.977979   1.79541964], p^2=4.00
'2*p' 4-Momentum, p=[5.76918796 0.75075375 1.955958   3.59083929], p^2=16.00
'3*p' 4-Momentum, p=[8.65378194 1.12613063 2.93393701 5.38625893], p^2=36.0

[Return to Table](#start)
<a id=A&M></a>
### Attributes and Methods

Now we can study some of the attributes of the Momentum class, there are six attriutes to the Momentum class:

    name: Returns a string with the name of the Momentum
    mu: Returns a numpy vector with the contravariant coordinates of the Momentum.
    _mu: Returns a numpy vector with the covariant coordinates of the Momentum.
    m2: Returns the dot product of the Momentum with itself (if it is On-Shell, it returns the mass squared).
    s: Returns a numpy matrix correspondint with the contraction of Momentum and the gamma matrices.
    I: Returns the vector p*I (each component is the coordinate of p multiplied by the 4x4 identity)

In [27]:
p = fmn.Momentum(10, name='electron')
print(p)
print('name:', p.name)
print('p^mu:', p.mu) 
print('p_mu:', p._mu)
print('p^2:', p.m2) #Same as p*p or p**2
print(p.s)
print(p.I)

'electron' 4-Momentum, p=[10.08188361 -1.12195356  0.06202025 -0.61785992], p^2=100.00
name: electron
p^mu: [10.08188361 -1.12195356  0.06202025 -0.61785992]
p_mu: [10.08188361  1.12195356 -0.06202025  0.61785992]
p^2: 99.99999999999999
[[ 10.08188361+0.j           0.        +0.j
    0.61785992+0.j           1.12195356+0.06202025j]
 [  0.        +0.j          10.08188361+0.j
    1.12195356-0.06202025j  -0.61785992+0.j        ]
 [ -0.61785992+0.j          -1.12195356-0.06202025j
  -10.08188361+0.j           0.        +0.j        ]
 [ -1.12195356+0.06202025j   0.61785992+0.j
    0.        +0.j         -10.08188361+0.j        ]]
[[[10.08188361  0.          0.          0.        ]
  [ 0.         10.08188361  0.          0.        ]
  [ 0.          0.         10.08188361  0.        ]
  [ 0.          0.          0.         10.08188361]]

 [[-1.12195356 -0.         -0.         -0.        ]
  [-0.         -1.12195356 -0.         -0.        ]
  [-0.         -0.         -1.12195356 -0.        ]


Finally there are some more methods that we can call, for example:

    p.dot(q): Returns the dot product (with Minkowski metric +---) of the 4-vectors P and Q.
    p.u(s): Returns a u spinor of 4-Momentum P and polarization s. Similarly there are this other 3 functions
    p.u_(s): Returns the adjoint u-spinor.
    p.v(s): Returns a v spinor.
    p.v_(s): Returns the adjoint v-spinor.
    p.e(s): Returns the contravariant polarization for spin 1 particles
    p.e_(s): Returns the covariant polarization

In [28]:
p, q = fmn.Momentum(1, name='p'), fmn.Momentum(2, name='q')
print(p)
print(p.dot(q), p*q) #They are the same
print(p.u(1))
print(p.u_(2))
print(p.v(2))
print(p.v_(2))
print(p.e(2))
print(p.e_(3))

'p' 4-Momentum, p=[ 3.36393867 -0.29138987  2.41576494 -2.09648637], p^2=1.00
8.64466707279382 8.64466707279382
[[ 2.08900423+0.j        ]
 [ 0.        +0.j        ]
 [-1.00358168+0.j        ]
 [-0.13948745+1.15641936j]]
[[ 0.        +0.j          2.08900423+0.j          0.13948745-1.15641936j
  -1.00358168+0.j        ]]
[[ 1.00358168+0.j        ]
 [ 0.13948745-1.15641936j]
 [-2.08900423-0.j        ]
 [ 0.        -0.j        ]]
[[1.00358168+0.j         0.13948745+1.15641936j 2.08900423+0.j
  0.        +0.j        ]]
[ 0.         -0.99280382 -0.11975212  0.        ]
[ 3.21186603  0.30518635 -2.53014448  2.19574898]


[Return to Table](#start)
<a id=Gamma></a>
## Gamma Matrices

This code also incorporates the Dirac $\gamma$ matrices (in 4 dimensions), with the *gamma* function and also with a vector form

In [29]:
#We can call the gamma matrices in several forms:
#Using the gamma fucntion
print('gamma function:', fmn.gamma(0), fmn.gamma(5), sep='\n', end='\n\n')

#Using the Gamma_matrices vector.
print('Gamma_matrices vector:', fmn.Gamma_matrices, sep='\n', end='\n\n')

#To get the covariant gamma matrices we can use the Gamma_matrices_cov vector
print('Gamma_matrices_cov vector:', fmn.Gamma_matrices_cov, sep='\n', end='\n\n')

gamma function:
[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]
[[0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]]

Gamma_matrices vector:
[[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
  [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]]

 [[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
  [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
  [ 0.+0.j -1.+0.j  0.+0.j  0.+0.j]
  [-1.+0.j  0.+0.j  0.+0.j  0.+0.j]]

 [[ 0.+0.j  0.+0.j  0.+0.j -0.-1.j]
  [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]
  [ 0.+0.j  0.+1.j  0.+0.j  0.+0.j]
  [-0.-1.j  0.+0.j  0.+0.j  0.+0.j]]

 [[ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
  [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]
  [-1.+0.j  0.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]]]

Gamma_matrices_cov vector:
[[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
  [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
  [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]]

 [[ 0.+0.j  0.+0

Also the sigma tensor $\sigma^{\mu\nu}=\frac{i}{2}[\gamma^\mu,\gamma^\nu]$

In [30]:
print('Sigma_matrix^1,2:', fmn.Sigma_matrices[1][2], sep='\n', end='\n\n')
print('Sigma_matrices:', fmn.Sigma_matrices, sep='\n')

Sigma_matrix^1,2:
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]]

Sigma_matrices:
[[[[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
   [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
   [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
   [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]]

  [[ 0.+0.j  0.+0.j  0.+0.j  0.+1.j]
   [ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]
   [ 0.+0.j  0.+1.j  0.+0.j  0.+0.j]
   [ 0.+1.j  0.+0.j  0.+0.j  0.+0.j]]

  [[ 0.+0.j  0.+0.j  0.+0.j  1.+0.j]
   [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
   [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
   [-1.+0.j  0.+0.j  0.+0.j  0.+0.j]]

  [[ 0.+0.j  0.+0.j  0.+1.j  0.+0.j]
   [ 0.+0.j  0.+0.j  0.+0.j -0.-1.j]
   [ 0.+1.j  0.+0.j  0.+0.j  0.+0.j]
   [ 0.+0.j -0.-1.j  0.+0.j  0.+0.j]]]


 [[[ 0.+0.j  0.+0.j  0.+0.j -0.-1.j]
   [ 0.+0.j  0.+0.j -0.-1.j  0.+0.j]
   [ 0.+0.j -0.-1.j  0.+0.j  0.+0.j]
   [-0.-1.j  0.+0.j  0.+0.j  0.+0.j]]

  [[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]
   [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j

[Return to Table](#start)
<a id=Physics></a>
## Physics functions

Also provides the following physical functions:

    dot product using minkowski metric: fmn.dot(a,b)
$$a\cdot b = a^0b^0 - a^1b^1 - a^2b^2 - a^3b^3$$

    square of a vector: fmn.square(a)
$$a^2 = a \cdot a$$

    Kronecker delta: fmn.delta(i,j)
$$\delta_{ij}=\begin{cases}
1 & \text{ if } i = j\\
0 & \text{ if } i \neq j
\end{cases}$$

    Minkowski metric: fmn.eta(m,n)

In [46]:
a = fmn.randn(4)
b = fmn.randn(4)

print(f'a = {a}', 
      f'b = {b}', 
      f'a * b = {fmn.dot(a,b)}',
     sep = '\n')

a = [-0.40336298  0.56273258  2.16500887 -1.09990734]
b = [ 1.3791912   1.42238964 -0.57874327 -0.92965886]
a * b = -1.1262939505551819


[Return to Table](#start)
<a id=Example_1></a>
## Lets give an example of how to use this code: 
Suppose we want to study the $e^-\mu^-$ elastic scattering. We can start by definig four 4-vectors:

In [32]:
m, M = 0.511, 105 #electron and muon masses.
p1, p2 = fmn.Momentum(m, name='initial electron'), fmn.Momentum(M, name='initial muon')
p3, p4 = fmn.Momentum(m, name='final electron'), fmn.Momentum(M, name='final muon')
print(p1, p2, p3, p4, sep='\n')

'initial electron' 4-Momentum, p=[ 2.4557353   1.25853288 -0.30704843 -2.02270391], p^2=0.26
'initial muon' 4-Momentum, p=[ 1.05014771e+02 -9.04245348e-02 -7.93650571e-01 -1.56974395e+00], p^2=11025.00
'final electron' 4-Momentum, p=[ 1.16775834 -0.02515572 -0.81987677 -0.65552103], p^2=0.26
'final muon' 4-Momentum, p=[105.01556558   0.60584281   0.51468212  -1.6239062 ], p^2=11025.00


Note that the 4-Momenta are generated randomly, and therefore we cannot assume conservation of 4-Momenta! (We will deal with this later). There is only one diagram contributing to the process, the t-channel. So we can define the 4-Momentum of the photon:

In [33]:
#Now we can define the photon 4-Momenta:
q = p1 - p3
print(q)
#If we want to give Q a name we can do it modifying its attribute, or by using the __sub__ method:
q.name = 'photon' #or
q = p1.__sub__(p3, 'photon')
print(q)

'initial electron - final electron' 4-Momentum, p=[ 1.28797695  1.2836886   0.51282834 -1.36718288], p^2=-2.12
'photon' 4-Momentum, p=[ 1.28797695  1.2836886   0.51282834 -1.36718288], p^2=-2.12


Now, the amplitude is given by the equation
$$\mathscr{M}_t=\frac{e^2}{q^2}[\bar{u}_3\gamma^\mu u_1][\bar{u}_4\gamma_\mu u_2]$$
To write this we need the $\gamma$ matrices, which are alredy implemented and can be called in two ways:

    gamma(i) #Returns the i=0,1,2,3 'contravariant' gamma matrix
    Gamma_matrices #Returns the i=0,1,2,3 'contravariant' gamma matrix
    Gamma_matrices_cov #Returns the i=0,1,2,3 'covariant' gamma matrix
Using this second we can now write the amplitude as:

In [34]:
e = fmn.sqrt(4 * fmn.pi / 137) #Electron and muon charge
G = fmn.Gamma_matrices
G_ = fmn.Gamma_matrices_cov
s1, s2, s3, s4 = 1, 2, 2, 1 #We choose a polarization of the particles arbitrarily.
A_1 = 0
for mu in range(4): #We need to sum over the mu index!
    A_1 += e**2 / q**2 * (p3.u_(s3)@G[mu]@p1.u(s1)) * (p4.u_(s4)@G_[mu]@p2.u(s2)) #We can use G_ to avoid using the metric

#Instead of G_ we can also use the metric defined as eta(mu, nu)
B = 0
for mu in range(4):
    for nu in range(4):
        B += e**2 / q**2 * (p3.u_(s3)@fmn.gamma(mu)@p1.u(s1)) * fmn.eta(mu, nu) * (p4.u_(s4)@fmn.gamma(nu)@p2.u(s2))
    
print(A_1, B)
print(fmn.comprv(A_1, B)) #They are equal, of course.

#An equivalent way to do this computation is using the power of numpy (this is not always possible and you must sum the 
#old way)

A_2 = e**2/  q**2 * np.sum( (p3.u_(s3)@G@p1.u(s1)) * (p4.u_(s4)@G_@p2.u(s2)) )

#And we can use the comprv function to be sure that this two amplitudes are indeed the same
fmn.comprv(A_1, A_2)

[[0.08078174-0.02957014j]] [[0.08078174-0.02957014j]]
[[ True]]


array([[ True]])

But generally we are not interested in the polarized amplitude, but rather in the unpolarized square amplitude. 
$$\left<|\mathscr{M}|^2\right> \equiv \frac{1}{N_{\text{initial}}}\sum_{\text{initial}}\sum_{\text{final}} |\mathscr{M}|^2$$
We can then simply sum over the polarizations in the old way, or use the *average* function.

In [35]:
A_1 = 0
for s1 in range(1,3):
    for s2 in range(1,3):
        for s3 in range(1,3):
            for s4 in range(1,3):
                A_1 += abs( e**2 / q**2 * np.sum( (p3.u_(s3)@G@p1.u(s1)) * (p4.u_(s4)@G_@p2.u(s2)) ) )**2
A_1 = 0.25 * A_1
print(A_1)

#But we can also use the average function, to do that we need to define the amplitude as a function of the polarizations:

def A(S): #The function must take only one argument with a list of polarizations
    s1, s2, s3, s4 = S
    return abs( e**2 / q**2 * np.sum(p3.u_(s3)@G@p1.u(s1) * p4.u_(s4)@G_@p2.u(s2)) )**2 #We want to average the square 
                                                                                         #of the amplitude.
A_2 = fmn.average(A, [2,2], [2,2])
print(A_2)

fmn.comprv(A_1, A_2)

749.3169593672296
749.3169593672299


True

The average function takes 3 arguments, the first one is a function of the polarizations (that must be introduced as a single list), then the other two are the total polarizations of the initial and final states. (1 for KG, 2 for Dirac particles and massless particles, 3 for massive vectorial bosons, etc.). 

The result of the average function is simply
$$\frac{1}{N_{\text{initial}}}\sum_{\text{initial}}\sum_{\text{final}} f$$


After some calculation one finds that
$$\left<|\mathscr{M}|^2\right>=\frac{8e^4}{q^4}\left[(p_1\cdot p_2)(p_3\cdot p_4)+(p_1\cdot p_4)(p_2\cdot p_3) - (p_1\cdot p_3)M^2-(p_2\cdot p_4)m^2+2m^2M^2\right]$$
with $m$ and $M$ the masses of the electron and the muon. How can we know if this is correct? Well, first we need to introduce this expresion to our code and then all that is left is to call the *comprv* function to see if this expresion really is equal to the averaged amplitude.

In [36]:
A_3 = 8 * e**4 / q**4 * ( (p1*p2)*(p3*p4) + (p1*p4)*(p2*p3) - (p1*p3)*M**2 - (p2*p4)*m**2 + 2*(m*M)**2 )

fmn.comprv(A_1, A_3, True)

749.3169593672296
749.3169593672294
2.2737367544323206e-13 3.0344125086297353e-16 True


True

And since this returns the value True (you can run the code multiple times, creating different random vectors and see that for all of them the result is True).

Now we can still simplify using the Mandelstam variables and write
$$\left<|\mathscr{M}|^2\right>=\frac{8e^4}{t^2}\left[\left(\frac{s-m^2-M^2}{2}\right)^2+\left(\frac{m^2+M^2-u}{2}\right)^2 - \left(\frac{2m^2-t}{2}\right)M^2-\left(\frac{2M^2-t}{2}\right)m^2+2m^2M^2\right]$$
$$\left<|\mathscr{M}|^2\right>=\frac{2e^4}{t^2}\left[s^2+u^2-4(M^2+m^2)(u+s)+6(m^2+M^2)^2\right]$$

We can define the mandelsam variables by hand, or use the specific function *Mandelstam*.

In [37]:
s, t, u = (p1+p2)**2, (p1-p3)**2, (p1-p4)**2
S, T, U = fmn.Mandelstam(p1, p2, p3, p4)

print(fmn.comprv(fmn.array([s, t, u]), fmn.array([S, T, U])))

A_4 = 2 * e**4 / t**2 * (s**2 + u**2 - 4*(M**2+m**2)*(u+s) + 6*(M**2+m**2)**2)

fmn.comprv(A_1, A_4, print_arg=True)

[ True  True  True]
749.3169593672296
1838.7172447466776
1089.400285379448 1.4538577724163697 False


False

###### The comprv function tells us that this is not equal to our previous expresions! 

Of course that's because we have implicitly used 4-Momentum conservation, but remember that we are generating random momenta and therefore they don't conserve the total momentum. When we need to impose 4-Momentum conservation we need to use a specific function; *Generate_scattering_2x2*, that will generate 4 random 4-momentum fullfilling 

In [38]:
particles = {'initial electron':m, 'initial muon':M, 'final electron':m, 'final muon':M}
p1, p2, p3, p4 = fmn.Generate_scattering_2x2(particles)
q = p1.__sub__(p3, 'photon')
print(p1, p2, sep='\n')

s, t, u = fmn.Mandelstam(p1, p2, p3, p4)
A_4 = 2 * e**4 / t**2 * (s**2 + u**2 - 2*(m**2+M**2)*(u+s-t) + 2*(m**2+M**2)**2)
fmn.comprv(fmn.average(A, [2,2], [2,2]), A_4, True)

'initial electron' 4-Momentum, p=[118.38025464 -52.59792409  56.47724674  89.76303554], p^2=0.26
'initial muon' 4-Momentum, p=[158.23597432  52.59792409 -56.47724674 -89.76303554], p^2=11025.00
0.017571443387771314
0.0175714433877713
1.3877787807814457e-17 7.897921361128806e-16 True


True

Now we have defined the *p1, p2, p3, p4* using the *Generate_scattering_2x2* function, which generates physical 4-Momenta in the CM reference frame (you can use the RF variable to generate physical momenta in the Lab frame). The arguments of the *Generate_scattering_2x2* are a list of the four masses and the values of *s* and *t*. And now the *comprv* function tells that the two expresions are equal.